# Generated by Django 5.1.1 on 2024-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CssParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.CharField(max_length=50)),
                ('padding', models.CharField(max_length=50)),
                ('block_size', models.CharField(max_length=50)),
            ],
        ),
    ]
